{"name": "test_case1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <pythonProject_pytest.testini.test_demo.TestDemo object at 0x00000227E4B26050>\n\n    def test_case1(self):\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_demo.py:11: AssertionError"}, "start": 1655457794926, "stop": 1655457794927, "uuid": "315b6e46-fecb-4ddb-aff9-82a4773afec5", "historyId": "7dbd611bc154f02fb6829547ecb4e3c1", "testCaseId": "c029aa06153a733679278b7f03559f80", "fullName": "test_demo.TestDemo#test_case1", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "KIKO-Wang"}, {"name": "thread", "value": "6276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}